name: Label issues

on:
  issues:
    types: [opened]

jobs:
  triage:
    runs-on: ubuntu-latest
    name: Triage
    if: |
      ${{ github.event.label.name == 'template: bug' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: 'Run issue validator'
        run: node ./.github/actions/issue-labeler/index.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
